name: jaxsim
channels:
  - conda-forge
dependencies:
  # ===========================
  # Dependencies from setup.cfg
  # ===========================
  - python >= 3.12.0
  - coloredlogs
  - jax >= 0.4.34
  - jaxlib >= 0.4.34
  - jaxlie >= 1.3.0
  - jax-dataclasses >= 1.4.0
  - optax >= 0.2.3
  - pptree
  - qpax
  - rod >= 0.3.3
  - trimesh
  - typing_extensions # python<3.12
  # ====================================
  # Optional dependencies from setup.cfg
  # ====================================
  # [style]
  - black == 24.*
  - isort
  - pre-commit
  # [testing]
  - idyntree >= 12.2.1
  - pytest
  - pytest-benchmark
  - pytest-icdiff
  - robot_descriptions >= 1.16.0
  - icub-models
  # [viz]
  - lxml
  - mediapy
  - mujoco >= 3.0.0
  - scipy >= 1.14.0
  # ==========================
  # Documentation dependencies
  # ==========================
  - cachecontrol
  - filecache
  - jinja2
  - myst-nb
  - pip
  - sphinx
  - sphinx-autodoc-typehints
  - sphinx-book-theme
  - sphinx-copybutton
  - sphinx-design
  - sphinx_fontawesome
  - sphinx-gallery
  - sphinx-jinja2-compat
  - sphinx-multiversion
  - sphinx_rtd_theme
  - sphinx-toolbox
  - icub-models
  # ========================================
  # Other dependencies for GitHub Codespaces
  # ========================================
  - ipython
  - pip:
    - sphinx-collections # TODO (flferretti): PR to conda-forge
