name: jaxsim
channels:
  - conda-forge
dependencies:
  # ===========================
  # Dependencies from setup.cfg
  # ===========================
  - python >= 3.12.0
  - coloredlogs
  - jax >= 0.4.13
  - jaxopt >= 0.8.0
  - jaxlib >= 0.4.13
  - jaxlie >= 1.3.0
  - jax-dataclasses >= 1.4.0
  - pptree
  - qpax
  - rod >= 0.3.0
  - typing_extensions # python<3.12
  # ====================================
  # Optional dependencies from setup.cfg
  # ====================================
  # [style]
  - black == 24.*
  - isort
  - pre-commit
  # [testing]
  - idyntree >= 12.2.1
  - pytest
  - pytest-icdiff
  - robot_descriptions
  # [viz]
  - lxml
  - mediapy
  - mujoco >= 3.0.0
  - scipy >= 1.14.0
  # ==========================
  # Documentation dependencies
  # ==========================
  - cachecontrol
  - enum_tools
  - filecache
  - filelock
  - jinja2
  - myst-nb
  - pip
  - sphinx
  - sphinx-autodoc-typehints
  - sphinx-book-theme
  - sphinx-copybutton
  - sphinx-design
  - sphinx_fontawesome
  - sphinx-gallery
  - sphinx-jinja2-compat
  - sphinx-multiversion
  - sphinx_rtd_theme
  - sphinx-toolbox
  # ========================================
  # Other dependencies for GitHub Codespaces
  # ========================================
  - mesalib
  - ipython
  - pip:
    - sphinx-collections # TODO (flferretti): PR to conda-forge
