name: Code Style

on:
  push:
    branches: [ "**" ]
    tags-ignore: [ "**" ]
  pull_request:
  workflow_dispatch:

jobs:

  black:
    name: black
    runs-on: ubuntu-latest

    steps:

      - name: "ğŸ”€ Checkout repository"
        uses: actions/checkout@v4

      - name: 'ğŸ Initialize Python'
        uses: actions/setup-python@v5
        with:
          python-version: "3.*"

      # Note: the black version needs to be in sync with what
      # specified in setup.cfg.
      - name: "ğŸ“ Black Code Formatter"
        uses: psf/black@stable
        with:
          options: "--check --diff --color"
          version: "~= 24.0"

  isort:
    name: isort
    runs-on: ubuntu-latest

    steps:

      - name: "ğŸ”€ Checkout repository"
        uses: actions/checkout@v4

      - name: 'ğŸ Initialize Python'
        uses: actions/setup-python@v5
        with:
          python-version: "3.*"

      # Workaround for https://github.com/isort/isort-action/issues/70
      - run: pip install colorama

      - name: "ğŸ“ isort"
        uses: isort/isort-action@master
        with:
          configuration: "--check --diff --color"

  ruff:
    name: ruff
    runs-on: ubuntu-latest

    steps:

      - name: "ğŸ”€ Checkout repository"
        uses: actions/checkout@v4

      - name: "ğŸ“ Ruff"
        uses: chartboost/ruff-action@v1
